// ./proto/message/v1/message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/message/v1/message.proto

package message

import (
	v1 "github.com/adrien19/chronoqueue/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Metadata_State int32

const (
	Message_Metadata_INVISIBLE Message_Metadata_State = 0
	Message_Metadata_PENDING   Message_Metadata_State = 1
	Message_Metadata_RUNNING   Message_Metadata_State = 2
	Message_Metadata_COMPLETED Message_Metadata_State = 3
	Message_Metadata_CANCELED  Message_Metadata_State = 4
	Message_Metadata_ERRORED   Message_Metadata_State = 5
)

// Enum value maps for Message_Metadata_State.
var (
	Message_Metadata_State_name = map[int32]string{
		0: "INVISIBLE",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "CANCELED",
		5: "ERRORED",
	}
	Message_Metadata_State_value = map[string]int32{
		"INVISIBLE": 0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"CANCELED":  4,
		"ERRORED":   5,
	}
)

func (x Message_Metadata_State) Enum() *Message_Metadata_State {
	p := new(Message_Metadata_State)
	*p = x
	return p
}

func (x Message_Metadata_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Metadata_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_v1_message_proto_enumTypes[0].Descriptor()
}

func (Message_Metadata_State) Type() protoreflect.EnumType {
	return &file_proto_message_v1_message_proto_enumTypes[0]
}

func (x Message_Metadata_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Metadata_State.Descriptor instead.
func (Message_Metadata_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Metadata      *Message_Metadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetMetadata() *Message_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Message_Metadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Payload              *v1.Payload            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	State                Message_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=chronoqueue.api.message.v1.Message_Metadata_State" json:"state,omitempty"`
	InvisibilityDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=invisibility_duration,json=invisibilityDuration,proto3" json:"invisibility_duration,omitempty"`
	AttemptsLeft         int32                  `protobuf:"varint,4,opt,name=attempts_left,json=attemptsLeft,proto3" json:"attempts_left,omitempty"`
	LeaseDuration        *durationpb.Duration   `protobuf:"bytes,5,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	LeaseExpiry          int64                  `protobuf:"varint,6,opt,name=lease_expiry,json=leaseExpiry,proto3" json:"lease_expiry,omitempty"`
	LeaseRenewalCount    int32                  `protobuf:"varint,7,opt,name=lease_renewal_count,json=leaseRenewalCount,proto3" json:"lease_renewal_count,omitempty"`
	InvisibilityExpiry   int64                  `protobuf:"varint,8,opt,name=invisibility_expiry,json=invisibilityExpiry,proto3" json:"invisibility_expiry,omitempty"`
	Priority             int64                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxAttempts          int32                  `protobuf:"varint,10,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Message_Metadata) Reset() {
	*x = Message_Metadata{}
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Metadata) ProtoMessage() {}

func (x *Message_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Metadata.ProtoReflect.Descriptor instead.
func (*Message_Metadata) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Metadata) GetPayload() *v1.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message_Metadata) GetState() Message_Metadata_State {
	if x != nil {
		return x.State
	}
	return Message_Metadata_INVISIBLE
}

func (x *Message_Metadata) GetInvisibilityDuration() *durationpb.Duration {
	if x != nil {
		return x.InvisibilityDuration
	}
	return nil
}

func (x *Message_Metadata) GetAttemptsLeft() int32 {
	if x != nil {
		return x.AttemptsLeft
	}
	return 0
}

func (x *Message_Metadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *Message_Metadata) GetLeaseExpiry() int64 {
	if x != nil {
		return x.LeaseExpiry
	}
	return 0
}

func (x *Message_Metadata) GetLeaseRenewalCount() int32 {
	if x != nil {
		return x.LeaseRenewalCount
	}
	return 0
}

func (x *Message_Metadata) GetInvisibilityExpiry() int64 {
	if x != nil {
		return x.InvisibilityExpiry
	}
	return 0
}

func (x *Message_Metadata) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Metadata) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

var File_proto_message_v1_message_proto protoreflect.FileDescriptor

const file_proto_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/message/v1/message.proto\x12\x1achronoqueue.api.message.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cproto/common/v1/common.proto\"\xdd\x05\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12H\n" +
	"\bmetadata\x18\x03 \x01(\v2,.chronoqueue.api.message.v1.Message.MetadataR\bmetadata\x1a\xe8\x04\n" +
	"\bMetadata\x12<\n" +
	"\apayload\x18\x01 \x01(\v2\".chronoqueue.api.common.v1.PayloadR\apayload\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.chronoqueue.api.message.v1.Message.Metadata.StateR\x05state\x12N\n" +
	"\x15invisibility_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x14invisibilityDuration\x12#\n" +
	"\rattempts_left\x18\x04 \x01(\x05R\fattemptsLeft\x12@\n" +
	"\x0elease_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12!\n" +
	"\flease_expiry\x18\x06 \x01(\x03R\vleaseExpiry\x12.\n" +
	"\x13lease_renewal_count\x18\a \x01(\x05R\x11leaseRenewalCount\x12/\n" +
	"\x13invisibility_expiry\x18\b \x01(\x03R\x12invisibilityExpiry\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x03R\bpriority\x12!\n" +
	"\fmax_attempts\x18\n" +
	" \x01(\x05R\vmaxAttempts\"Z\n" +
	"\x05State\x12\r\n" +
	"\tINVISIBLE\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x04\x12\v\n" +
	"\aERRORED\x10\x05B8Z6github.com/adrien19/chronoqueue/api/message/v1;messageb\x06proto3"

var (
	file_proto_message_v1_message_proto_rawDescOnce sync.Once
	file_proto_message_v1_message_proto_rawDescData []byte
)

func file_proto_message_v1_message_proto_rawDescGZIP() []byte {
	file_proto_message_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)))
	})
	return file_proto_message_v1_message_proto_rawDescData
}

var file_proto_message_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_message_v1_message_proto_goTypes = []any{
	(Message_Metadata_State)(0), // 0: chronoqueue.api.message.v1.Message.Metadata.State
	(*Message)(nil),             // 1: chronoqueue.api.message.v1.Message
	(*Message_Metadata)(nil),    // 2: chronoqueue.api.message.v1.Message.Metadata
	(*v1.Payload)(nil),          // 3: chronoqueue.api.common.v1.Payload
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_proto_message_v1_message_proto_depIdxs = []int32{
	2, // 0: chronoqueue.api.message.v1.Message.metadata:type_name -> chronoqueue.api.message.v1.Message.Metadata
	3, // 1: chronoqueue.api.message.v1.Message.Metadata.payload:type_name -> chronoqueue.api.common.v1.Payload
	0, // 2: chronoqueue.api.message.v1.Message.Metadata.state:type_name -> chronoqueue.api.message.v1.Message.Metadata.State
	4, // 3: chronoqueue.api.message.v1.Message.Metadata.invisibility_duration:type_name -> google.protobuf.Duration
	4, // 4: chronoqueue.api.message.v1.Message.Metadata.lease_duration:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_message_v1_message_proto_init() }
func file_proto_message_v1_message_proto_init() {
	if File_proto_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_message_v1_message_proto_depIdxs,
		EnumInfos:         file_proto_message_v1_message_proto_enumTypes,
		MessageInfos:      file_proto_message_v1_message_proto_msgTypes,
	}.Build()
	File_proto_message_v1_message_proto = out.File
	file_proto_message_v1_message_proto_goTypes = nil
	file_proto_message_v1_message_proto_depIdxs = nil
}
