// ChronoQueue Message API v1
//
// This file defines the core Message structure and its lifecycle states.
// Messages are the fundamental unit of work in ChronoQueue.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/message/v1/message.proto

package message

import (
	v1 "github.com/adrien19/chronoqueue/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the message lifecycle stage.
//
// State transitions:
//
//	POST -> INVISIBLE (if scheduled_time is set)
//	POST -> PENDING (if no scheduled_time or scheduled_time is past)
//	INVISIBLE -> PENDING (when scheduled_time arrives)
//	PENDING -> RUNNING (when worker calls GetNextMessage)
//	RUNNING -> COMPLETED (when worker calls AcknowledgeMessage)
//	RUNNING -> PENDING (if lease expires without acknowledgment)
//	RUNNING -> ERRORED (if max_attempts exhausted)
//	* -> CANCELED (when CancelMessage is called)
//
// Important: Messages in COMPLETED, CANCELED, and ERRORED states are terminal
// and won't be processed again (unless explicitly requeued from DLQ).
type Message_Metadata_State int32

const (
	Message_Metadata_INVISIBLE Message_Metadata_State = 0 // Scheduled for future, not yet visible to workers
	Message_Metadata_PENDING   Message_Metadata_State = 1 // Ready to be consumed by workers (visible in queue)
	Message_Metadata_RUNNING   Message_Metadata_State = 2 // Currently being processed (lease acquired)
	Message_Metadata_COMPLETED Message_Metadata_State = 3 // Successfully processed and acknowledged (terminal)
	Message_Metadata_CANCELED  Message_Metadata_State = 4 // Manually canceled (terminal)
	Message_Metadata_ERRORED   Message_Metadata_State = 5 // Failed after all retries, moved to DLQ (terminal)
)

// Enum value maps for Message_Metadata_State.
var (
	Message_Metadata_State_name = map[int32]string{
		0: "INVISIBLE",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "CANCELED",
		5: "ERRORED",
	}
	Message_Metadata_State_value = map[string]int32{
		"INVISIBLE": 0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"CANCELED":  4,
		"ERRORED":   5,
	}
)

func (x Message_Metadata_State) Enum() *Message_Metadata_State {
	p := new(Message_Metadata_State)
	*p = x
	return p
}

func (x Message_Metadata_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Metadata_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_v1_message_proto_enumTypes[0].Descriptor()
}

func (Message_Metadata_State) Type() protoreflect.EnumType {
	return &file_proto_message_v1_message_proto_enumTypes[0]
}

func (x Message_Metadata_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Metadata_State.Descriptor instead.
func (Message_Metadata_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Message represents a unit of work in ChronoQueue.
//
// A message encapsulates:
// - Your business data (payload)
// - Execution metadata (state, priority, retries)
// - Scheduling information (when to execute)
// - Processing guarantees (leases, acknowledgments)
//
// Lifecycle:
//  1. INVISIBLE: Message is scheduled for future execution or waiting to become visible
//  2. PENDING: Message is ready to be consumed by a worker
//  3. RUNNING: Message is actively being processed (worker has acquired a lease)
//  4. COMPLETED: Message was successfully processed and acknowledged
//  5. ERRORED: Message failed all retry attempts and moved to DLQ
//  6. CANCELED: Message was manually canceled before processing
//
// Example usage:
//
//	// Post a message
//	msg := &message.Message{
//	    MessageId: "task-123",
//	    Metadata: &message.Message_Metadata{
//	        Payload: yourPayload,
//	        Priority: 100,                        // Higher = processed first
//	        MaxAttempts: 3,                       // Retry up to 3 times
//	        LeaseDuration: durationpb.New(30*time.Second), // 30s to process
//	        ScheduledTime: timestamppb.New(executeAt),     // When to execute
//	    },
//	}
//
//	// Process a message
//	msg, err := client.GetNextMessage(ctx, queueName)
//	// ... do work ...
//	client.AcknowledgeMessage(ctx, queueName, msg.MessageId, streamEntryID)
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id: Unique identifier for this message within its queue.
	// Must be unique per queue. Used for deduplication and idempotency.
	// If you retry posting the same message_id, ChronoQueue returns the existing message.
	// Recommended format: UUID, task ID, or "{entity_type}:{entity_id}".
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// metadata: All message execution and lifecycle information.
	Metadata      *Message_Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetMetadata() *Message_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata contains all message execution and lifecycle information.
type Message_Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload: The business data and metadata to be processed.
	// This is what your workers receive and act upon.
	Payload *v1.Payload            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	State   Message_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=chronoqueue.api.message.v1.Message_Metadata_State" json:"state,omitempty"`
	// attempts_left: Number of retry attempts remaining before moving to DLQ.
	// Decrements with each processing failure. When reaches 0 and fails, moves to ERRORED state.
	// Set max_attempts when posting to control retry behavior.
	AttemptsLeft int32 `protobuf:"varint,4,opt,name=attempts_left,json=attemptsLeft,proto3" json:"attempts_left,omitempty"`
	// lease_duration: How long a worker can process this message before the lease expires.
	// After this duration, if not acknowledged or renewed, message returns to PENDING state.
	// Workers should call RenewLease or SendHeartbeat if processing takes longer.
	// Typical values: 30s for quick tasks, 5m for longer processing.
	LeaseDuration *durationpb.Duration `protobuf:"bytes,5,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	// lease_expiry: Unix timestamp (milliseconds) when the current lease expires.
	// Managed automatically by ChronoQueue. Workers can monitor this to know when to renew.
	// If current time > lease_expiry, message will be reclaimed and made PENDING again.
	LeaseExpiry int64 `protobuf:"varint,6,opt,name=lease_expiry,json=leaseExpiry,proto3" json:"lease_expiry,omitempty"`
	// lease_renewal_count: Number of times the lease has been renewed for this processing attempt.
	// Useful for detecting stuck/zombie workers that keep renewing without completing.
	// Consider implementing a max renewal limit in your worker logic.
	LeaseRenewalCount int32 `protobuf:"varint,7,opt,name=lease_renewal_count,json=leaseRenewalCount,proto3" json:"lease_renewal_count,omitempty"`
	// priority: Message priority score (0-2147483647, higher = processed first).
	// ChronoQueue uses priority streams (high: ≥70, medium: ≥30, low: <30).
	// Messages with the same priority are processed FIFO.
	// Use for: urgent tasks (100), normal (50), background (10).
	Priority int64 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	// max_attempts: Maximum number of processing attempts before moving to DLQ.
	// If omitted, uses queue's default_max_attempts.
	// Set to -1 for infinite retries (use with caution).
	// Common values: 1 (no retry), 3 (standard), 5 (persistent), -1 (infinite).
	MaxAttempts int32 `protobuf:"varint,10,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// scheduled_time: When this message should become visible for processing.
	// If set to a future time, message enters INVISIBLE state until that time.
	// If omitted or past, message immediately becomes PENDING.
	// Use for: scheduled tasks, delayed execution, rate limiting, backoff strategies.
	// Example: Schedule order fulfillment for tomorrow at 9 AM.
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	// priority_level: Internal priority level for stream routing (auto-calculated).
	// Managed by ChronoQueue based on priority score. Read-only from client perspective.
	// Used internally for routing to high/medium/low priority streams.
	PriorityLevel int32 `protobuf:"varint,21,opt,name=priority_level,json=priorityLevel,proto3" json:"priority_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Metadata) Reset() {
	*x = Message_Metadata{}
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Metadata) ProtoMessage() {}

func (x *Message_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Metadata.ProtoReflect.Descriptor instead.
func (*Message_Metadata) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Metadata) GetPayload() *v1.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message_Metadata) GetState() Message_Metadata_State {
	if x != nil {
		return x.State
	}
	return Message_Metadata_INVISIBLE
}

func (x *Message_Metadata) GetAttemptsLeft() int32 {
	if x != nil {
		return x.AttemptsLeft
	}
	return 0
}

func (x *Message_Metadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *Message_Metadata) GetLeaseExpiry() int64 {
	if x != nil {
		return x.LeaseExpiry
	}
	return 0
}

func (x *Message_Metadata) GetLeaseRenewalCount() int32 {
	if x != nil {
		return x.LeaseRenewalCount
	}
	return 0
}

func (x *Message_Metadata) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Metadata) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Message_Metadata) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *Message_Metadata) GetPriorityLevel() int32 {
	if x != nil {
		return x.PriorityLevel
	}
	return 0
}

var File_proto_message_v1_message_proto protoreflect.FileDescriptor

const file_proto_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/message/v1/message.proto\x12\x1achronoqueue.api.message.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproto/common/v1/common.proto\"\xfe\x05\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12H\n" +
	"\bmetadata\x18\x03 \x01(\v2,.chronoqueue.api.message.v1.Message.MetadataR\bmetadata\x1a\x89\x05\n" +
	"\bMetadata\x12<\n" +
	"\apayload\x18\x01 \x01(\v2\".chronoqueue.api.common.v1.PayloadR\apayload\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.chronoqueue.api.message.v1.Message.Metadata.StateR\x05state\x12#\n" +
	"\rattempts_left\x18\x04 \x01(\x05R\fattemptsLeft\x12@\n" +
	"\x0elease_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12!\n" +
	"\flease_expiry\x18\x06 \x01(\x03R\vleaseExpiry\x12.\n" +
	"\x13lease_renewal_count\x18\a \x01(\x05R\x11leaseRenewalCount\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x03R\bpriority\x12!\n" +
	"\fmax_attempts\x18\n" +
	" \x01(\x05R\vmaxAttempts\x12A\n" +
	"\x0escheduled_time\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12%\n" +
	"\x0epriority_level\x18\x15 \x01(\x05R\rpriorityLevel\"Z\n" +
	"\x05State\x12\r\n" +
	"\tINVISIBLE\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x04\x12\v\n" +
	"\aERRORED\x10\x05J\x04\b\x03\x10\x04J\x04\b\b\x10\tR\x15invisibility_durationR\x13invisibility_expiryB8Z6github.com/adrien19/chronoqueue/api/message/v1;messageb\x06proto3"

var (
	file_proto_message_v1_message_proto_rawDescOnce sync.Once
	file_proto_message_v1_message_proto_rawDescData []byte
)

func file_proto_message_v1_message_proto_rawDescGZIP() []byte {
	file_proto_message_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)))
	})
	return file_proto_message_v1_message_proto_rawDescData
}

var file_proto_message_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_message_v1_message_proto_goTypes = []any{
	(Message_Metadata_State)(0),   // 0: chronoqueue.api.message.v1.Message.Metadata.State
	(*Message)(nil),               // 1: chronoqueue.api.message.v1.Message
	(*Message_Metadata)(nil),      // 2: chronoqueue.api.message.v1.Message.Metadata
	(*v1.Payload)(nil),            // 3: chronoqueue.api.common.v1.Payload
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_message_v1_message_proto_depIdxs = []int32{
	2, // 0: chronoqueue.api.message.v1.Message.metadata:type_name -> chronoqueue.api.message.v1.Message.Metadata
	3, // 1: chronoqueue.api.message.v1.Message.Metadata.payload:type_name -> chronoqueue.api.common.v1.Payload
	0, // 2: chronoqueue.api.message.v1.Message.Metadata.state:type_name -> chronoqueue.api.message.v1.Message.Metadata.State
	4, // 3: chronoqueue.api.message.v1.Message.Metadata.lease_duration:type_name -> google.protobuf.Duration
	5, // 4: chronoqueue.api.message.v1.Message.Metadata.scheduled_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_message_v1_message_proto_init() }
func file_proto_message_v1_message_proto_init() {
	if File_proto_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_message_v1_message_proto_depIdxs,
		EnumInfos:         file_proto_message_v1_message_proto_enumTypes,
		MessageInfos:      file_proto_message_v1_message_proto_msgTypes,
	}.Build()
	File_proto_message_v1_message_proto = out.File
	file_proto_message_v1_message_proto_goTypes = nil
	file_proto_message_v1_message_proto_depIdxs = nil
}
