// ChronoQueue Queue API v1
//
// This file defines queue structures and configurations.
// Queues are named containers for messages with specific processing behaviors.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/queue/v1/queue.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueType defines the message consumption pattern.
//
// Choose based on your use case:
// - SIMPLE: Most common. Multiple workers can consume in parallel.
// - EXCLUSIVE: Single-consumer queues for ordered processing or exclusive access.
type QueueType int32

const (
	QueueType_SIMPLE    QueueType = 0 // Multiple workers can consume messages concurrently (default)
	QueueType_EXCLUSIVE QueueType = 1 // Only one worker can consume from this queue at a time
)

// Enum value maps for QueueType.
var (
	QueueType_name = map[int32]string{
		0: "SIMPLE",
		1: "EXCLUSIVE",
	}
	QueueType_value = map[string]int32{
		"SIMPLE":    0,
		"EXCLUSIVE": 1,
	}
)

func (x QueueType) Enum() *QueueType {
	p := new(QueueType)
	*p = x
	return p
}

func (x QueueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_queue_v1_queue_proto_enumTypes[0].Descriptor()
}

func (QueueType) Type() protoreflect.EnumType {
	return &file_proto_queue_v1_queue_proto_enumTypes[0]
}

func (x QueueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueType.Descriptor instead.
func (QueueType) EnumDescriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

// FairnessPolicy determines how messages with different priorities compete for processing.
//
// Priority fairness is critical in systems with both urgent and background tasks.
// Without fairness policies, low-priority messages could starve indefinitely.
type FairnessPolicy int32

const (
	FairnessPolicy_STRICT   FairnessPolicy = 0 // Process strictly by priority (high before medium before low)
	FairnessPolicy_WEIGHTED FairnessPolicy = 1 // Balance priority with fairness using weights
	FairnessPolicy_AGING    FairnessPolicy = 2 // Boost priority of messages waiting too long
	FairnessPolicy_HYBRID   FairnessPolicy = 3 // Combines weighted and aging strategies
)

// Enum value maps for FairnessPolicy.
var (
	FairnessPolicy_name = map[int32]string{
		0: "STRICT",
		1: "WEIGHTED",
		2: "AGING",
		3: "HYBRID",
	}
	FairnessPolicy_value = map[string]int32{
		"STRICT":   0,
		"WEIGHTED": 1,
		"AGING":    2,
		"HYBRID":   3,
	}
)

func (x FairnessPolicy) Enum() *FairnessPolicy {
	p := new(FairnessPolicy)
	*p = x
	return p
}

func (x FairnessPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FairnessPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_queue_v1_queue_proto_enumTypes[1].Descriptor()
}

func (FairnessPolicy) Type() protoreflect.EnumType {
	return &file_proto_queue_v1_queue_proto_enumTypes[1]
}

func (x FairnessPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FairnessPolicy.Descriptor instead.
func (FairnessPolicy) EnumDescriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{1}
}

// QueueMetadata defines the configuration and behavior of a queue.
//
// This controls:
// - Message processing rules (retries, leases, priorities)
// - Data validation (schemas, content types)
// - Error handling (dead letter queues)
// - Consumer patterns (exclusivity, fairness)
//
// Example - Create a queue for order processing:
//
//	metadata := &queue.QueueMetadata{
//	    Type: queue.QueueType_SIMPLE,
//	    DefaultMaxAttempts: 3,
//	    LeaseDuration: durationpb.New(5*time.Minute),
//	    DeadLetterQueueName: "order-processing-dlq",
//	    AutoCreateDlq: true,
//	    SchemaId: "order.v1",
//	    SchemaRequired: true,
//	    MaxPayloadSize: 1024 * 512,  // 512KB
//	    AllowedContentTypes: []string{"application/json"},
//	}
type QueueMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: Determines message consumption pattern.
	// SIMPLE: Multiple workers process concurrently (most common).
	// EXCLUSIVE: Single worker processes sequentially (ensures order).
	Type QueueType `protobuf:"varint,1,opt,name=type,proto3,enum=chronoqueue.api.queue.v1.QueueType" json:"type,omitempty"`
	// default_max_attempts: Default retry count for messages without explicit max_attempts.
	// Messages failing this many times move to the dead letter queue.
	// Common values: 1 (no retry), 3 (standard), 5 (aggressive retry).
	// Set to -1 for infinite retries (use with extreme caution).
	DefaultMaxAttempts int32 `protobuf:"varint,2,opt,name=default_max_attempts,json=defaultMaxAttempts,proto3" json:"default_max_attempts,omitempty"`
	// lease_duration: Default time workers have to process a message.
	// If a worker doesn't acknowledge within this time, message returns to queue.
	// Workers can renew leases for longer operations via RenewLease/SendHeartbeat.
	// Common values: 30s (quick tasks), 5m (standard), 30m (long-running).
	// Balance between: too short = unnecessary retries, too long = slow failure detection.
	LeaseDuration *durationpb.Duration `protobuf:"bytes,3,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	// exclusivity_key: For EXCLUSIVE queues, this key ensures single-consumer access.
	// Only one worker with a matching exclusivity key can consume from this queue.
	// Leave empty for non-exclusive queues.
	// Use cases: ordered processing, singleton workers, distributed locks.
	ExclusivityKey string `protobuf:"bytes,4,opt,name=exclusivity_key,json=exclusivityKey,proto3" json:"exclusivity_key,omitempty"`
	// dead_letter_queue_name: Name of the DLQ for messages that exhaust retries.
	// Messages that fail after max_attempts are moved here for investigation.
	// Naming convention: "{original-queue}-dlq" or "{original-queue}-errors"
	// Access DLQ messages via DLQ APIs: GetDLQMessage, ListDLQMessages, RequeueDLQMessage.
	DeadLetterQueueName string `protobuf:"bytes,6,opt,name=dead_letter_queue_name,json=deadLetterQueueName,proto3" json:"dead_letter_queue_name,omitempty"`
	// auto_create_dlq: If true, ChronoQueue automatically creates the DLQ if it doesn't exist.
	// Recommended: true for production (ensures no messages are lost).
	// Set to false if you want to manually control DLQ creation and configuration.
	AutoCreateDlq bool `protobuf:"varint,7,opt,name=auto_create_dlq,json=autoCreateDlq,proto3" json:"auto_create_dlq,omitempty"`
	// schema_id: Default schema for validating messages posted to this queue.
	// All messages must conform to this schema (if schema_required is true).
	// Helps ensure data quality and catch errors before processing.
	// Example: "order.created.v1", "user.profile.v2"
	// Register schemas via RegisterSchema API.
	SchemaId string `protobuf:"bytes,8,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// schema_required: If true, all messages must have a valid schema and pass validation.
	// Messages without a schema or failing validation are rejected.
	// Use in production for critical data pipelines to prevent bad data.
	// Set to false for development or when schema validation isn't needed.
	SchemaRequired bool `protobuf:"varint,9,opt,name=schema_required,json=schemaRequired,proto3" json:"schema_required,omitempty"`
	// max_payload_size: Maximum size of message payload in bytes.
	// Messages exceeding this limit are rejected.
	// If not set or 0, uses system default (typically 256KB).
	// Increase for large payloads (e.g., 1MB = 1048576).
	// Note: Very large messages impact performance - consider using references instead.
	MaxPayloadSize int32 `protobuf:"varint,10,opt,name=max_payload_size,json=maxPayloadSize,proto3" json:"max_payload_size,omitempty"`
	// allowed_content_types: List of permitted MIME types for message payloads.
	// Empty list = all content types allowed (default).
	// Examples: ["application/json"], ["application/json", "application/xml"]
	// Use to enforce data format standards across your organization.
	AllowedContentTypes []string `protobuf:"bytes,11,rep,name=allowed_content_types,json=allowedContentTypes,proto3" json:"allowed_content_types,omitempty"`
	// priority_config: Advanced priority scheduling configuration.
	// Controls how messages with different priorities are processed.
	// Most users can omit this - defaults work well for common cases.
	// Customize for: complex fairness requirements, aging prevention, weighted priorities.
	PriorityConfig *PriorityConfig `protobuf:"bytes,12,opt,name=priority_config,json=priorityConfig,proto3" json:"priority_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueMetadata) Reset() {
	*x = QueueMetadata{}
	mi := &file_proto_queue_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetadata) ProtoMessage() {}

func (x *QueueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetadata.ProtoReflect.Descriptor instead.
func (*QueueMetadata) Descriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMetadata) GetType() QueueType {
	if x != nil {
		return x.Type
	}
	return QueueType_SIMPLE
}

func (x *QueueMetadata) GetDefaultMaxAttempts() int32 {
	if x != nil {
		return x.DefaultMaxAttempts
	}
	return 0
}

func (x *QueueMetadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *QueueMetadata) GetExclusivityKey() string {
	if x != nil {
		return x.ExclusivityKey
	}
	return ""
}

func (x *QueueMetadata) GetDeadLetterQueueName() string {
	if x != nil {
		return x.DeadLetterQueueName
	}
	return ""
}

func (x *QueueMetadata) GetAutoCreateDlq() bool {
	if x != nil {
		return x.AutoCreateDlq
	}
	return false
}

func (x *QueueMetadata) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *QueueMetadata) GetSchemaRequired() bool {
	if x != nil {
		return x.SchemaRequired
	}
	return false
}

func (x *QueueMetadata) GetMaxPayloadSize() int32 {
	if x != nil {
		return x.MaxPayloadSize
	}
	return 0
}

func (x *QueueMetadata) GetAllowedContentTypes() []string {
	if x != nil {
		return x.AllowedContentTypes
	}
	return nil
}

func (x *QueueMetadata) GetPriorityConfig() *PriorityConfig {
	if x != nil {
		return x.PriorityConfig
	}
	return nil
}

// PriorityConfig provides fine-grained control over priority-based processing.
//
// Example - Weighted fairness with aging:
//
//	config := &queue.PriorityConfig{
//	    Policy: queue.FairnessPolicy_HYBRID,
//	    PriorityWeights: map[int32]int32{
//	        100: 70,  // High priority: 70% of processing capacity
//	        50:  20,  // Medium priority: 20%
//	        10:  10,  // Low priority: 10%
//	    },
//	    AgeBoostThreshold: durationpb.New(30*time.Minute),  // Boost after 30min wait
//	    AgeBoostMultiplier: 2,  // Double the priority every 30min
//	}
type PriorityConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policy: The fairness strategy to use.
	// See FairnessPolicy enum for detailed descriptions.
	Policy FairnessPolicy `protobuf:"varint,1,opt,name=policy,proto3,enum=chronoqueue.api.queue.v1.FairnessPolicy" json:"policy,omitempty"`
	// priority_weights: For WEIGHTED/HYBRID policies, maps priority levels to weights.
	// Key: priority level (e.g., 100, 50, 10)
	// Value: relative weight (e.g., 70, 20, 10 = 70% high, 20% medium, 10% low)
	// Weights are relative - they're normalized to percentages.
	PriorityWeights map[int32]int32 `protobuf:"bytes,2,rep,name=priority_weights,json=priorityWeights,proto3" json:"priority_weights,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// age_boost_threshold: For AGING/HYBRID policies, how long before boosting priority.
	// Messages waiting longer than this duration get their priority boosted.
	// Prevents indefinite starvation of low-priority messages.
	// Typical values: 15m (aggressive), 30m (standard), 1h (relaxed).
	AgeBoostThreshold *durationpb.Duration `protobuf:"bytes,3,opt,name=age_boost_threshold,json=ageBoostThreshold,proto3" json:"age_boost_threshold,omitempty"`
	// age_boost_multiplier: For AGING/HYBRID policies, how much to boost priority.
	// Priority multiplied by this factor every age_boost_threshold period.
	// Example: multiplier=2, threshold=30m means priority doubles every 30 minutes.
	// Typical values: 1.5 (gentle), 2 (standard), 3 (aggressive).
	AgeBoostMultiplier int32 `protobuf:"varint,4,opt,name=age_boost_multiplier,json=ageBoostMultiplier,proto3" json:"age_boost_multiplier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PriorityConfig) Reset() {
	*x = PriorityConfig{}
	mi := &file_proto_queue_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityConfig) ProtoMessage() {}

func (x *PriorityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityConfig.ProtoReflect.Descriptor instead.
func (*PriorityConfig) Descriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *PriorityConfig) GetPolicy() FairnessPolicy {
	if x != nil {
		return x.Policy
	}
	return FairnessPolicy_STRICT
}

func (x *PriorityConfig) GetPriorityWeights() map[int32]int32 {
	if x != nil {
		return x.PriorityWeights
	}
	return nil
}

func (x *PriorityConfig) GetAgeBoostThreshold() *durationpb.Duration {
	if x != nil {
		return x.AgeBoostThreshold
	}
	return nil
}

func (x *PriorityConfig) GetAgeBoostMultiplier() int32 {
	if x != nil {
		return x.AgeBoostMultiplier
	}
	return 0
}

// Queue represents a named message container with specific processing behavior.
//
// Queues are the primary organizational unit in ChronoQueue.
// Create separate queues for different types of work to:
// - Isolate failures (one queue's DLQ doesn't affect others)
// - Apply different processing rules (retries, priorities, leases)
// - Scale consumers independently
// - Organize by domain (orders, notifications, analytics)
//
// Example queue names:
// - "order-processing"          // Core business logic
// - "email-notifications"       // User communications
// - "webhook-deliveries"        // External API calls
// - "data-analytics-high"       // Time-sensitive analytics
// - "cleanup-tasks-low"         // Background maintenance
type Queue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: Unique identifier for this queue.
	// Must be unique across your ChronoQueue instance.
	// Naming convention: lowercase, hyphens, descriptive
	// Examples: "order-processing", "email-sender", "webhook-delivery"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// metadata: Queue configuration and behavior settings.
	Metadata      *QueueMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_proto_queue_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetMetadata() *QueueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_queue_v1_queue_proto protoreflect.FileDescriptor

const file_proto_queue_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/queue/v1/queue.proto\x12\x18chronoqueue.api.queue.v1\x1a\x1egoogle/protobuf/duration.proto\"\xd6\x04\n" +
	"\rQueueMetadata\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.chronoqueue.api.queue.v1.QueueTypeR\x04type\x120\n" +
	"\x14default_max_attempts\x18\x02 \x01(\x05R\x12defaultMaxAttempts\x12@\n" +
	"\x0elease_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12'\n" +
	"\x0fexclusivity_key\x18\x04 \x01(\tR\x0eexclusivityKey\x123\n" +
	"\x16dead_letter_queue_name\x18\x06 \x01(\tR\x13deadLetterQueueName\x12&\n" +
	"\x0fauto_create_dlq\x18\a \x01(\bR\rautoCreateDlq\x12\x1b\n" +
	"\tschema_id\x18\b \x01(\tR\bschemaId\x12'\n" +
	"\x0fschema_required\x18\t \x01(\bR\x0eschemaRequired\x12(\n" +
	"\x10max_payload_size\x18\n" +
	" \x01(\x05R\x0emaxPayloadSize\x122\n" +
	"\x15allowed_content_types\x18\v \x03(\tR\x13allowedContentTypes\x12Q\n" +
	"\x0fpriority_config\x18\f \x01(\v2(.chronoqueue.api.queue.v1.PriorityConfigR\x0epriorityConfigJ\x04\b\x05\x10\x06R\x15invisibility_duration\"\xfd\x02\n" +
	"\x0ePriorityConfig\x12@\n" +
	"\x06policy\x18\x01 \x01(\x0e2(.chronoqueue.api.queue.v1.FairnessPolicyR\x06policy\x12h\n" +
	"\x10priority_weights\x18\x02 \x03(\v2=.chronoqueue.api.queue.v1.PriorityConfig.PriorityWeightsEntryR\x0fpriorityWeights\x12I\n" +
	"\x13age_boost_threshold\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11ageBoostThreshold\x120\n" +
	"\x14age_boost_multiplier\x18\x04 \x01(\x05R\x12ageBoostMultiplier\x1aB\n" +
	"\x14PriorityWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"`\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\bmetadata\x18\x02 \x01(\v2'.chronoqueue.api.queue.v1.QueueMetadataR\bmetadata*&\n" +
	"\tQueueType\x12\n" +
	"\n" +
	"\x06SIMPLE\x10\x00\x12\r\n" +
	"\tEXCLUSIVE\x10\x01*A\n" +
	"\x0eFairnessPolicy\x12\n" +
	"\n" +
	"\x06STRICT\x10\x00\x12\f\n" +
	"\bWEIGHTED\x10\x01\x12\t\n" +
	"\x05AGING\x10\x02\x12\n" +
	"\n" +
	"\x06HYBRID\x10\x03B4Z2github.com/adrien19/chronoqueue/api/queue/v1;queueb\x06proto3"

var (
	file_proto_queue_v1_queue_proto_rawDescOnce sync.Once
	file_proto_queue_v1_queue_proto_rawDescData []byte
)

func file_proto_queue_v1_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_v1_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_v1_queue_proto_rawDesc), len(file_proto_queue_v1_queue_proto_rawDesc)))
	})
	return file_proto_queue_v1_queue_proto_rawDescData
}

var file_proto_queue_v1_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_queue_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_queue_v1_queue_proto_goTypes = []any{
	(QueueType)(0),              // 0: chronoqueue.api.queue.v1.QueueType
	(FairnessPolicy)(0),         // 1: chronoqueue.api.queue.v1.FairnessPolicy
	(*QueueMetadata)(nil),       // 2: chronoqueue.api.queue.v1.QueueMetadata
	(*PriorityConfig)(nil),      // 3: chronoqueue.api.queue.v1.PriorityConfig
	(*Queue)(nil),               // 4: chronoqueue.api.queue.v1.Queue
	nil,                         // 5: chronoqueue.api.queue.v1.PriorityConfig.PriorityWeightsEntry
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_proto_queue_v1_queue_proto_depIdxs = []int32{
	0, // 0: chronoqueue.api.queue.v1.QueueMetadata.type:type_name -> chronoqueue.api.queue.v1.QueueType
	6, // 1: chronoqueue.api.queue.v1.QueueMetadata.lease_duration:type_name -> google.protobuf.Duration
	3, // 2: chronoqueue.api.queue.v1.QueueMetadata.priority_config:type_name -> chronoqueue.api.queue.v1.PriorityConfig
	1, // 3: chronoqueue.api.queue.v1.PriorityConfig.policy:type_name -> chronoqueue.api.queue.v1.FairnessPolicy
	5, // 4: chronoqueue.api.queue.v1.PriorityConfig.priority_weights:type_name -> chronoqueue.api.queue.v1.PriorityConfig.PriorityWeightsEntry
	6, // 5: chronoqueue.api.queue.v1.PriorityConfig.age_boost_threshold:type_name -> google.protobuf.Duration
	2, // 6: chronoqueue.api.queue.v1.Queue.metadata:type_name -> chronoqueue.api.queue.v1.QueueMetadata
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_queue_v1_queue_proto_init() }
func file_proto_queue_v1_queue_proto_init() {
	if File_proto_queue_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_v1_queue_proto_rawDesc), len(file_proto_queue_v1_queue_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_queue_v1_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_v1_queue_proto_depIdxs,
		EnumInfos:         file_proto_queue_v1_queue_proto_enumTypes,
		MessageInfos:      file_proto_queue_v1_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_v1_queue_proto = out.File
	file_proto_queue_v1_queue_proto_goTypes = nil
	file_proto_queue_v1_queue_proto_depIdxs = nil
}
