// ./chronoq/proto/queue/v1/queue.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/queue/v1/queue.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueType int32

const (
	QueueType_SIMPLE    QueueType = 0
	QueueType_EXCLUSIVE QueueType = 1
)

// Enum value maps for QueueType.
var (
	QueueType_name = map[int32]string{
		0: "SIMPLE",
		1: "EXCLUSIVE",
	}
	QueueType_value = map[string]int32{
		"SIMPLE":    0,
		"EXCLUSIVE": 1,
	}
)

func (x QueueType) Enum() *QueueType {
	p := new(QueueType)
	*p = x
	return p
}

func (x QueueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_queue_v1_queue_proto_enumTypes[0].Descriptor()
}

func (QueueType) Type() protoreflect.EnumType {
	return &file_proto_queue_v1_queue_proto_enumTypes[0]
}

func (x QueueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueType.Descriptor instead.
func (QueueType) EnumDescriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

type QueueMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 QueueType              `protobuf:"varint,1,opt,name=type,proto3,enum=chronoqueue.api.queue.v1.QueueType" json:"type,omitempty"`
	DequeueAttempts      int32                  `protobuf:"varint,2,opt,name=dequeue_attempts,json=dequeueAttempts,proto3" json:"dequeue_attempts,omitempty"`
	LeaseDuration        *durationpb.Duration   `protobuf:"bytes,3,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	ExclusivityKey       string                 `protobuf:"bytes,4,opt,name=exclusivity_key,json=exclusivityKey,proto3" json:"exclusivity_key,omitempty"`
	InvisibilityDuration *durationpb.Duration   `protobuf:"bytes,5,opt,name=invisibility_duration,json=invisibilityDuration,proto3" json:"invisibility_duration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueueMetadata) Reset() {
	*x = QueueMetadata{}
	mi := &file_proto_queue_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetadata) ProtoMessage() {}

func (x *QueueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetadata.ProtoReflect.Descriptor instead.
func (*QueueMetadata) Descriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMetadata) GetType() QueueType {
	if x != nil {
		return x.Type
	}
	return QueueType_SIMPLE
}

func (x *QueueMetadata) GetDequeueAttempts() int32 {
	if x != nil {
		return x.DequeueAttempts
	}
	return 0
}

func (x *QueueMetadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *QueueMetadata) GetExclusivityKey() string {
	if x != nil {
		return x.ExclusivityKey
	}
	return ""
}

func (x *QueueMetadata) GetInvisibilityDuration() *durationpb.Duration {
	if x != nil {
		return x.InvisibilityDuration
	}
	return nil
}

type Queue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *QueueMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_proto_queue_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_proto_queue_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetMetadata() *QueueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_queue_v1_queue_proto protoreflect.FileDescriptor

const file_proto_queue_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/queue/v1/queue.proto\x12\x18chronoqueue.api.queue.v1\x1a\x1egoogle/protobuf/duration.proto\"\xae\x02\n" +
	"\rQueueMetadata\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.chronoqueue.api.queue.v1.QueueTypeR\x04type\x12)\n" +
	"\x10dequeue_attempts\x18\x02 \x01(\x05R\x0fdequeueAttempts\x12@\n" +
	"\x0elease_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12'\n" +
	"\x0fexclusivity_key\x18\x04 \x01(\tR\x0eexclusivityKey\x12N\n" +
	"\x15invisibility_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x14invisibilityDuration\"`\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\bmetadata\x18\x02 \x01(\v2'.chronoqueue.api.queue.v1.QueueMetadataR\bmetadata*&\n" +
	"\tQueueType\x12\n" +
	"\n" +
	"\x06SIMPLE\x10\x00\x12\r\n" +
	"\tEXCLUSIVE\x10\x01B4Z2github.com/adrien19/chronoqueue/api/queue/v1;queueb\x06proto3"

var (
	file_proto_queue_v1_queue_proto_rawDescOnce sync.Once
	file_proto_queue_v1_queue_proto_rawDescData []byte
)

func file_proto_queue_v1_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_v1_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_v1_queue_proto_rawDesc), len(file_proto_queue_v1_queue_proto_rawDesc)))
	})
	return file_proto_queue_v1_queue_proto_rawDescData
}

var file_proto_queue_v1_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_queue_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_queue_v1_queue_proto_goTypes = []any{
	(QueueType)(0),              // 0: chronoqueue.api.queue.v1.QueueType
	(*QueueMetadata)(nil),       // 1: chronoqueue.api.queue.v1.QueueMetadata
	(*Queue)(nil),               // 2: chronoqueue.api.queue.v1.Queue
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_proto_queue_v1_queue_proto_depIdxs = []int32{
	0, // 0: chronoqueue.api.queue.v1.QueueMetadata.type:type_name -> chronoqueue.api.queue.v1.QueueType
	3, // 1: chronoqueue.api.queue.v1.QueueMetadata.lease_duration:type_name -> google.protobuf.Duration
	3, // 2: chronoqueue.api.queue.v1.QueueMetadata.invisibility_duration:type_name -> google.protobuf.Duration
	1, // 3: chronoqueue.api.queue.v1.Queue.metadata:type_name -> chronoqueue.api.queue.v1.QueueMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_queue_v1_queue_proto_init() }
func file_proto_queue_v1_queue_proto_init() {
	if File_proto_queue_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_v1_queue_proto_rawDesc), len(file_proto_queue_v1_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_queue_v1_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_v1_queue_proto_depIdxs,
		EnumInfos:         file_proto_queue_v1_queue_proto_enumTypes,
		MessageInfos:      file_proto_queue_v1_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_v1_queue_proto = out.File
	file_proto_queue_v1_queue_proto_goTypes = nil
	file_proto_queue_v1_queue_proto_depIdxs = nil
}
