// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chronoqueue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChronoQueueClient is the client API for ChronoQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChronoQueueClient interface {
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error)
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error)
	GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error)
	AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error)
	RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error)
	PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error)
	GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error)
	SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error)
}

type chronoQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewChronoQueueClient(cc grpc.ClientConnInterface) ChronoQueueClient {
	return &chronoQueueClient{cc}
}

func (c *chronoQueueClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error) {
	out := new(DeleteQueueResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error) {
	out := new(GetNextMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error) {
	out := new(AcknowledgeMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error) {
	out := new(RenewMessageLeaseResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error) {
	out := new(PeekQueueMessagesResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error) {
	out := new(GetQueueStateResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error) {
	out := new(SendMessageHeartBeatResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/SendMessageHeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronoQueueServer is the server API for ChronoQueue service.
// All implementations must embed UnimplementedChronoQueueServer
// for forward compatibility
type ChronoQueueServer interface {
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error)
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error)
	AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error)
	RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error)
	PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error)
	GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error)
	SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error)
	mustEmbedUnimplementedChronoQueueServer()
}

// UnimplementedChronoQueueServer must be embedded to have forward compatible implementations.
type UnimplementedChronoQueueServer struct {
}

func (UnimplementedChronoQueueServer) CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedChronoQueueServer) DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQueue not implemented")
}
func (UnimplementedChronoQueueServer) PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedChronoQueueServer) GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextMessage not implemented")
}
func (UnimplementedChronoQueueServer) AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessage not implemented")
}
func (UnimplementedChronoQueueServer) RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewMessageLease not implemented")
}
func (UnimplementedChronoQueueServer) PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeekQueueMessages not implemented")
}
func (UnimplementedChronoQueueServer) GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueState not implemented")
}
func (UnimplementedChronoQueueServer) SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageHeartBeat not implemented")
}
func (UnimplementedChronoQueueServer) mustEmbedUnimplementedChronoQueueServer() {}

// UnsafeChronoQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronoQueueServer will
// result in compilation errors.
type UnsafeChronoQueueServer interface {
	mustEmbedUnimplementedChronoQueueServer()
}

func RegisterChronoQueueServer(s grpc.ServiceRegistrar, srv ChronoQueueServer) {
	s.RegisterService(&ChronoQueue_ServiceDesc, srv)
}

func _ChronoQueue_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_DeleteQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).DeleteQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).DeleteQueue(ctx, req.(*DeleteQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetNextMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetNextMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetNextMessage(ctx, req.(*GetNextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_AcknowledgeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).AcknowledgeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).AcknowledgeMessage(ctx, req.(*AcknowledgeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_RenewMessageLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewMessageLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).RenewMessageLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).RenewMessageLease(ctx, req.(*RenewMessageLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_PeekQueueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekQueueMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).PeekQueueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).PeekQueueMessages(ctx, req.(*PeekQueueMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetQueueState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetQueueState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetQueueState(ctx, req.(*GetQueueStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_SendMessageHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageHeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).SendMessageHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/SendMessageHeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).SendMessageHeartBeat(ctx, req.(*SendMessageHeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronoQueue_ServiceDesc is the grpc.ServiceDesc for ChronoQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronoQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronoqueue.api.chronoqueue.v1.ChronoQueue",
	HandlerType: (*ChronoQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _ChronoQueue_CreateQueue_Handler,
		},
		{
			MethodName: "DeleteQueue",
			Handler:    _ChronoQueue_DeleteQueue_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _ChronoQueue_PostMessage_Handler,
		},
		{
			MethodName: "GetNextMessage",
			Handler:    _ChronoQueue_GetNextMessage_Handler,
		},
		{
			MethodName: "AcknowledgeMessage",
			Handler:    _ChronoQueue_AcknowledgeMessage_Handler,
		},
		{
			MethodName: "RenewMessageLease",
			Handler:    _ChronoQueue_RenewMessageLease_Handler,
		},
		{
			MethodName: "PeekQueueMessages",
			Handler:    _ChronoQueue_PeekQueueMessages_Handler,
		},
		{
			MethodName: "GetQueueState",
			Handler:    _ChronoQueue_GetQueueState_Handler,
		},
		{
			MethodName: "SendMessageHeartBeat",
			Handler:    _ChronoQueue_SendMessageHeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chronoqueue/v1/service.proto",
}
