// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chronoqueue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChronoQueueClient is the client API for ChronoQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChronoQueueClient interface {
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error)
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error)
	GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error)
	AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error)
	RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error)
	PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error)
	GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error)
	SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error)
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error)
	ResumeSchedule(ctx context.Context, in *ResumeScheduleRequest, opts ...grpc.CallOption) (*ResumeScheduleResponse, error)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	GetScheduleHistory(ctx context.Context, in *GetScheduleHistoryRequest, opts ...grpc.CallOption) (*GetScheduleHistoryResponse, error)
}

type chronoQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewChronoQueueClient(cc grpc.ClientConnInterface) ChronoQueueClient {
	return &chronoQueueClient{cc}
}

func (c *chronoQueueClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error) {
	out := new(DeleteQueueResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error) {
	out := new(GetNextMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error) {
	out := new(AcknowledgeMessageResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error) {
	out := new(RenewMessageLeaseResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error) {
	out := new(PeekQueueMessagesResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error) {
	out := new(GetQueueStateResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error) {
	out := new(SendMessageHeartBeatResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/SendMessageHeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ListQueues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error) {
	out := new(CreateScheduleResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error) {
	out := new(PauseScheduleResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PauseSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) ResumeSchedule(ctx context.Context, in *ResumeScheduleRequest, opts ...grpc.CallOption) (*ResumeScheduleResponse, error) {
	out := new(ResumeScheduleResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ResumeSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ListSchedules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronoQueueClient) GetScheduleHistory(ctx context.Context, in *GetScheduleHistoryRequest, opts ...grpc.CallOption) (*GetScheduleHistoryResponse, error) {
	out := new(GetScheduleHistoryResponse)
	err := c.cc.Invoke(ctx, "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetScheduleHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronoQueueServer is the server API for ChronoQueue service.
// All implementations must embed UnimplementedChronoQueueServer
// for forward compatibility
type ChronoQueueServer interface {
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error)
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error)
	AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error)
	RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error)
	PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error)
	GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error)
	SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error)
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error)
	ResumeSchedule(context.Context, *ResumeScheduleRequest) (*ResumeScheduleResponse, error)
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	GetScheduleHistory(context.Context, *GetScheduleHistoryRequest) (*GetScheduleHistoryResponse, error)
	mustEmbedUnimplementedChronoQueueServer()
}

// UnimplementedChronoQueueServer must be embedded to have forward compatible implementations.
type UnimplementedChronoQueueServer struct {
}

func (UnimplementedChronoQueueServer) CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedChronoQueueServer) DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQueue not implemented")
}
func (UnimplementedChronoQueueServer) PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedChronoQueueServer) GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextMessage not implemented")
}
func (UnimplementedChronoQueueServer) AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessage not implemented")
}
func (UnimplementedChronoQueueServer) RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewMessageLease not implemented")
}
func (UnimplementedChronoQueueServer) PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeekQueueMessages not implemented")
}
func (UnimplementedChronoQueueServer) GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueState not implemented")
}
func (UnimplementedChronoQueueServer) SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageHeartBeat not implemented")
}
func (UnimplementedChronoQueueServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedChronoQueueServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedChronoQueueServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedChronoQueueServer) PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseSchedule not implemented")
}
func (UnimplementedChronoQueueServer) ResumeSchedule(context.Context, *ResumeScheduleRequest) (*ResumeScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeSchedule not implemented")
}
func (UnimplementedChronoQueueServer) GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedChronoQueueServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedChronoQueueServer) GetScheduleHistory(context.Context, *GetScheduleHistoryRequest) (*GetScheduleHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduleHistory not implemented")
}
func (UnimplementedChronoQueueServer) mustEmbedUnimplementedChronoQueueServer() {}

// UnsafeChronoQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronoQueueServer will
// result in compilation errors.
type UnsafeChronoQueueServer interface {
	mustEmbedUnimplementedChronoQueueServer()
}

func RegisterChronoQueueServer(s grpc.ServiceRegistrar, srv ChronoQueueServer) {
	s.RegisterService(&ChronoQueue_ServiceDesc, srv)
}

func _ChronoQueue_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_DeleteQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).DeleteQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).DeleteQueue(ctx, req.(*DeleteQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetNextMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetNextMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetNextMessage(ctx, req.(*GetNextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_AcknowledgeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).AcknowledgeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).AcknowledgeMessage(ctx, req.(*AcknowledgeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_RenewMessageLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewMessageLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).RenewMessageLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).RenewMessageLease(ctx, req.(*RenewMessageLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_PeekQueueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekQueueMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).PeekQueueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).PeekQueueMessages(ctx, req.(*PeekQueueMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetQueueState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetQueueState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetQueueState(ctx, req.(*GetQueueStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_SendMessageHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageHeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).SendMessageHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/SendMessageHeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).SendMessageHeartBeat(ctx, req.(*SendMessageHeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ListQueues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_PauseSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).PauseSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/PauseSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).PauseSchedule(ctx, req.(*PauseScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_ResumeSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).ResumeSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ResumeSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).ResumeSchedule(ctx, req.(*ResumeScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/ListSchedules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronoQueue_GetScheduleHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronoQueueServer).GetScheduleHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetScheduleHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronoQueueServer).GetScheduleHistory(ctx, req.(*GetScheduleHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronoQueue_ServiceDesc is the grpc.ServiceDesc for ChronoQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronoQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronoqueue.api.chronoqueue.v1.ChronoQueue",
	HandlerType: (*ChronoQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _ChronoQueue_CreateQueue_Handler,
		},
		{
			MethodName: "DeleteQueue",
			Handler:    _ChronoQueue_DeleteQueue_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _ChronoQueue_PostMessage_Handler,
		},
		{
			MethodName: "GetNextMessage",
			Handler:    _ChronoQueue_GetNextMessage_Handler,
		},
		{
			MethodName: "AcknowledgeMessage",
			Handler:    _ChronoQueue_AcknowledgeMessage_Handler,
		},
		{
			MethodName: "RenewMessageLease",
			Handler:    _ChronoQueue_RenewMessageLease_Handler,
		},
		{
			MethodName: "PeekQueueMessages",
			Handler:    _ChronoQueue_PeekQueueMessages_Handler,
		},
		{
			MethodName: "GetQueueState",
			Handler:    _ChronoQueue_GetQueueState_Handler,
		},
		{
			MethodName: "SendMessageHeartBeat",
			Handler:    _ChronoQueue_SendMessageHeartBeat_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _ChronoQueue_ListQueues_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _ChronoQueue_CreateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _ChronoQueue_DeleteSchedule_Handler,
		},
		{
			MethodName: "PauseSchedule",
			Handler:    _ChronoQueue_PauseSchedule_Handler,
		},
		{
			MethodName: "ResumeSchedule",
			Handler:    _ChronoQueue_ResumeSchedule_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _ChronoQueue_GetSchedule_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _ChronoQueue_ListSchedules_Handler,
		},
		{
			MethodName: "GetScheduleHistory",
			Handler:    _ChronoQueue_GetScheduleHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chronoqueue/v1/service.proto",
}
