// ./proto/schedule/v1/schedule.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/schedule/v1/schedule.proto

package schedule

import (
	v11 "github.com/adrien19/chronoqueue/api/common/v1"
	v1 "github.com/adrien19/chronoqueue/api/message/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schedule_Metadata_State int32

const (
	Schedule_Metadata_SCHEDULED Schedule_Metadata_State = 0
	Schedule_Metadata_CANCELED  Schedule_Metadata_State = 1
	Schedule_Metadata_ERRORED   Schedule_Metadata_State = 2
	Schedule_Metadata_PAUSED    Schedule_Metadata_State = 3
)

// Enum value maps for Schedule_Metadata_State.
var (
	Schedule_Metadata_State_name = map[int32]string{
		0: "SCHEDULED",
		1: "CANCELED",
		2: "ERRORED",
		3: "PAUSED",
	}
	Schedule_Metadata_State_value = map[string]int32{
		"SCHEDULED": 0,
		"CANCELED":  1,
		"ERRORED":   2,
		"PAUSED":    3,
	}
)

func (x Schedule_Metadata_State) Enum() *Schedule_Metadata_State {
	p := new(Schedule_Metadata_State)
	*p = x
	return p
}

func (x Schedule_Metadata_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schedule_Metadata_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schedule_v1_schedule_proto_enumTypes[0].Descriptor()
}

func (Schedule_Metadata_State) Type() protoreflect.EnumType {
	return &file_proto_schedule_v1_schedule_proto_enumTypes[0]
}

func (x Schedule_Metadata_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schedule_Metadata_State.Descriptor instead.
func (Schedule_Metadata_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Metadata      *Schedule_Metadata     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetMetadata() *Schedule_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScheduleHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*v1.Message          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	NextRun       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	LastRun       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistory) Reset() {
	*x = ScheduleHistory{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistory) ProtoMessage() {}

func (x *ScheduleHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistory.ProtoReflect.Descriptor instead.
func (*ScheduleHistory) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleHistory) GetMessages() []*v1.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ScheduleHistory) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleHistory) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *ScheduleHistory) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *ScheduleHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduleHistory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Schedule_Metadata struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Payload        *v11.Payload            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	State          Schedule_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=chronoqueue.api.schedule.v1.Schedule_Metadata_State" json:"state,omitempty"`
	CronSchedule   string                  `protobuf:"bytes,3,opt,name=cron_schedule,json=cronSchedule,proto3" json:"cron_schedule,omitempty"`
	QueueName      string                  `protobuf:"bytes,4,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageIds     []string                `protobuf:"bytes,5,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	NextRun        *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	LastRun        *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	CreatedAt      *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExclusivityKey string                  `protobuf:"bytes,10,opt,name=exclusivity_key,json=exclusivityKey,proto3" json:"exclusivity_key,omitempty"`
	StateMessage   string                  `protobuf:"bytes,11,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
	Priority       int64                   `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	HasMaxMessages bool                    `protobuf:"varint,13,opt,name=has_max_messages,json=hasMaxMessages,proto3" json:"has_max_messages,omitempty"`
	MaxMessages    int64                   `protobuf:"varint,14,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	LeaseDuration  *durationpb.Duration    `protobuf:"bytes,15,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule_Metadata) Reset() {
	*x = Schedule_Metadata{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_Metadata) ProtoMessage() {}

func (x *Schedule_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_Metadata.ProtoReflect.Descriptor instead.
func (*Schedule_Metadata) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Schedule_Metadata) GetPayload() *v11.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Schedule_Metadata) GetState() Schedule_Metadata_State {
	if x != nil {
		return x.State
	}
	return Schedule_Metadata_SCHEDULED
}

func (x *Schedule_Metadata) GetCronSchedule() string {
	if x != nil {
		return x.CronSchedule
	}
	return ""
}

func (x *Schedule_Metadata) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *Schedule_Metadata) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *Schedule_Metadata) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *Schedule_Metadata) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *Schedule_Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Schedule_Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Schedule_Metadata) GetExclusivityKey() string {
	if x != nil {
		return x.ExclusivityKey
	}
	return ""
}

func (x *Schedule_Metadata) GetStateMessage() string {
	if x != nil {
		return x.StateMessage
	}
	return ""
}

func (x *Schedule_Metadata) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Schedule_Metadata) GetHasMaxMessages() bool {
	if x != nil {
		return x.HasMaxMessages
	}
	return false
}

func (x *Schedule_Metadata) GetMaxMessages() int64 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *Schedule_Metadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

var File_proto_schedule_v1_schedule_proto protoreflect.FileDescriptor

const file_proto_schedule_v1_schedule_proto_rawDesc = "" +
	"\n" +
	" proto/schedule/v1/schedule.proto\x12\x1bchronoqueue.api.schedule.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cproto/common/v1/common.proto\x1a\x1eproto/message/v1/message.proto\"\x8f\a\n" +
	"\bSchedule\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12J\n" +
	"\bmetadata\x18\x02 \x01(\v2..chronoqueue.api.schedule.v1.Schedule.MetadataR\bmetadata\x1a\x95\x06\n" +
	"\bMetadata\x12<\n" +
	"\apayload\x18\x01 \x01(\v2\".chronoqueue.api.common.v1.PayloadR\apayload\x12J\n" +
	"\x05state\x18\x02 \x01(\x0e24.chronoqueue.api.schedule.v1.Schedule.Metadata.StateR\x05state\x12#\n" +
	"\rcron_schedule\x18\x03 \x01(\tR\fcronSchedule\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x04 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vmessage_ids\x18\x05 \x03(\tR\n" +
	"messageIds\x125\n" +
	"\bnext_run\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x125\n" +
	"\blast_run\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fexclusivity_key\x18\n" +
	" \x01(\tR\x0eexclusivityKey\x12#\n" +
	"\rstate_message\x18\v \x01(\tR\fstateMessage\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x03R\bpriority\x12(\n" +
	"\x10has_max_messages\x18\r \x01(\bR\x0ehasMaxMessages\x12!\n" +
	"\fmax_messages\x18\x0e \x01(\x03R\vmaxMessages\x12@\n" +
	"\x0elease_duration\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\"=\n" +
	"\x05State\x12\r\n" +
	"\tSCHEDULED\x10\x00\x12\f\n" +
	"\bCANCELED\x10\x01\x12\v\n" +
	"\aERRORED\x10\x02\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x03\"\xd7\x02\n" +
	"\x0fScheduleHistory\x12?\n" +
	"\bmessages\x18\x01 \x03(\v2#.chronoqueue.api.message.v1.MessageR\bmessages\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x125\n" +
	"\bnext_run\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x125\n" +
	"\blast_run\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB:Z8github.com/adrien19/chronoqueue/api/schedule/v1;scheduleb\x06proto3"

var (
	file_proto_schedule_v1_schedule_proto_rawDescOnce sync.Once
	file_proto_schedule_v1_schedule_proto_rawDescData []byte
)

func file_proto_schedule_v1_schedule_proto_rawDescGZIP() []byte {
	file_proto_schedule_v1_schedule_proto_rawDescOnce.Do(func() {
		file_proto_schedule_v1_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schedule_v1_schedule_proto_rawDesc), len(file_proto_schedule_v1_schedule_proto_rawDesc)))
	})
	return file_proto_schedule_v1_schedule_proto_rawDescData
}

var file_proto_schedule_v1_schedule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_schedule_v1_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_schedule_v1_schedule_proto_goTypes = []any{
	(Schedule_Metadata_State)(0),  // 0: chronoqueue.api.schedule.v1.Schedule.Metadata.State
	(*Schedule)(nil),              // 1: chronoqueue.api.schedule.v1.Schedule
	(*ScheduleHistory)(nil),       // 2: chronoqueue.api.schedule.v1.ScheduleHistory
	(*Schedule_Metadata)(nil),     // 3: chronoqueue.api.schedule.v1.Schedule.Metadata
	(*v1.Message)(nil),            // 4: chronoqueue.api.message.v1.Message
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v11.Payload)(nil),           // 6: chronoqueue.api.common.v1.Payload
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_proto_schedule_v1_schedule_proto_depIdxs = []int32{
	3,  // 0: chronoqueue.api.schedule.v1.Schedule.metadata:type_name -> chronoqueue.api.schedule.v1.Schedule.Metadata
	4,  // 1: chronoqueue.api.schedule.v1.ScheduleHistory.messages:type_name -> chronoqueue.api.message.v1.Message
	5,  // 2: chronoqueue.api.schedule.v1.ScheduleHistory.next_run:type_name -> google.protobuf.Timestamp
	5,  // 3: chronoqueue.api.schedule.v1.ScheduleHistory.last_run:type_name -> google.protobuf.Timestamp
	5,  // 4: chronoqueue.api.schedule.v1.ScheduleHistory.created_at:type_name -> google.protobuf.Timestamp
	5,  // 5: chronoqueue.api.schedule.v1.ScheduleHistory.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: chronoqueue.api.schedule.v1.Schedule.Metadata.payload:type_name -> chronoqueue.api.common.v1.Payload
	0,  // 7: chronoqueue.api.schedule.v1.Schedule.Metadata.state:type_name -> chronoqueue.api.schedule.v1.Schedule.Metadata.State
	5,  // 8: chronoqueue.api.schedule.v1.Schedule.Metadata.next_run:type_name -> google.protobuf.Timestamp
	5,  // 9: chronoqueue.api.schedule.v1.Schedule.Metadata.last_run:type_name -> google.protobuf.Timestamp
	5,  // 10: chronoqueue.api.schedule.v1.Schedule.Metadata.created_at:type_name -> google.protobuf.Timestamp
	5,  // 11: chronoqueue.api.schedule.v1.Schedule.Metadata.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 12: chronoqueue.api.schedule.v1.Schedule.Metadata.lease_duration:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_schedule_v1_schedule_proto_init() }
func file_proto_schedule_v1_schedule_proto_init() {
	if File_proto_schedule_v1_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedule_v1_schedule_proto_rawDesc), len(file_proto_schedule_v1_schedule_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_schedule_v1_schedule_proto_goTypes,
		DependencyIndexes: file_proto_schedule_v1_schedule_proto_depIdxs,
		EnumInfos:         file_proto_schedule_v1_schedule_proto_enumTypes,
		MessageInfos:      file_proto_schedule_v1_schedule_proto_msgTypes,
	}.Build()
	File_proto_schedule_v1_schedule_proto = out.File
	file_proto_schedule_v1_schedule_proto_goTypes = nil
	file_proto_schedule_v1_schedule_proto_depIdxs = nil
}
