version: '3.5'

services:
  chronoqueuesvc:
    container_name: chronoqueue_container
    hostname: chronoqueue_container
    build:
      context: ..
      dockerfile: ./images/Dockerfile
    # env_file: .env
    environment:
      - SERVER_MODE=development
      - REDIS_ADDR=redis_container:6379
      - REDIS_PASSWORD=
      - REDIS_USERNAME=
      - REDIS_DB=0
      - REDIS_TLS_ENABLED=false
      - SERVER_CERT_PATH=/secrets/server.crt
      - SERVER_KEY_PATH=/secrets/server.key
      - CA_CERT_PATH=/secrets/ca.crt
      - CHRONOQUEUE_TLS_ENABLED=false
      - ENABLE_ENCRYPTION=true
      - ENCRYPTION_KEY_SOURCE_TYPE=LOCAL
      - ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    depends_on:
      - redis
    networks:
      - demo_network
    volumes:
      - ../certs:/secrets
    ports:
      - "9000:9000"
      - "8080:8080"

  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
      - '8001:8001' # Redis Insight port
    networks:
      - demo_network
    volumes:
      - redis_data:/data
    restart: unless-stopped

networks:
  demo_network:
    # external: true
    name: demo_network
    driver: bridge

volumes:
    redis_data:
