version: '3.5'

services:
  chronoqueuesvc:
    container_name: chronoqueue_container
    hostname: chronoqueue_container
    build:
      context: ..
      dockerfile: ./images/Dockerfile
    # env_file: .env
    environment:
      - SERVER_MODE=development
      - HOST=chronoqueue_container
      - AUTH_SERVICE_HOST=authentication
      - REDIS_HOST=host.docker.internal
      - REDIS_ADDR=host.docker.internal:6379
      - REDIS_PASSWORD=
      - REDIS_USERNAME=
      - REDIS_DB=0
      - REDIS_TLS_ENABLED=false
      - SERVER_CERT_PATH=/secrets/server.crt
      - SERVER_KEY_PATH=/secrets/server.key
      - CA_CERT_PATH=/secrets/ca.crt
      - CHRONOQUEUE_TLS_ENABLED=false
      - ENABLE_ENCRYPTION=true
      - ENCRYPTION_KEY_SOURCE_TYPE=LOCAL
      - ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    # depends_on:
    #   - cachesvc
      # - authenticationsvc
    # networks:
    #   - chronoqueue_network
    volumes:
      - ../certs:/secrets
    ports:
      - "9000:9000"
      - "9001:9001"

#   cachesvc:
#     image: bitnami/redis:latest
#     container_name: cachesvc_container
#     environment:
#       - ALLOW_EMPTY_PASSWORD=yes
#     ports:
#       - '6379:6379'
#     networks:
#       - chronoqueue_network
#     volumes: 
#       - cachesvc:/data
#     restart: unless-stopped

# networks:
#   chronoqueue_network:
#     # external: true

# volumes:
#     cachesvc:
