// ./proto/queueservice/v1/request_response.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/queueservice/v1/request_response.proto

package queueservice

import (
	v11 "github.com/adrien19/chronoqueue/api/message/v1"
	v1 "github.com/adrien19/chronoqueue/api/queue/v1"
	v12 "github.com/adrien19/chronoqueue/api/schedule/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create queue
type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      *v1.QueueMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueRequest) GetMetadata() *v1.QueueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Delete queue by name
type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Post a message to the queue
type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Message       *v11.Message           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{4}
}

func (x *PostMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *PostMessageRequest) GetMessage() *v11.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PostMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{5}
}

func (x *PostMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get the next message on the queue
type GetNextMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueName      string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	LeaseDuration  *durationpb.Duration   `protobuf:"bytes,2,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	ExclusivityKey string                 `protobuf:"bytes,3,opt,name=exclusivity_key,json=exclusivityKey,proto3" json:"exclusivity_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNextMessageRequest) Reset() {
	*x = GetNextMessageRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextMessageRequest) ProtoMessage() {}

func (x *GetNextMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextMessageRequest.ProtoReflect.Descriptor instead.
func (*GetNextMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{6}
}

func (x *GetNextMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetNextMessageRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *GetNextMessageRequest) GetExclusivityKey() string {
	if x != nil {
		return x.ExclusivityKey
	}
	return ""
}

type GetNextMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *v11.Message           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextMessageResponse) Reset() {
	*x = GetNextMessageResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextMessageResponse) ProtoMessage() {}

func (x *GetNextMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextMessageResponse.ProtoReflect.Descriptor instead.
func (*GetNextMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{7}
}

func (x *GetNextMessageResponse) GetMessage() *v11.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Acknowledge the message on the queue
type AcknowledgeMessageRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	QueueName     string                     `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                     `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	State         v11.Message_Metadata_State `protobuf:"varint,3,opt,name=state,proto3,enum=chronoqueue.api.message.v1.Message_Metadata_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeMessageRequest) Reset() {
	*x = AcknowledgeMessageRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeMessageRequest) ProtoMessage() {}

func (x *AcknowledgeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeMessageRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{8}
}

func (x *AcknowledgeMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *AcknowledgeMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AcknowledgeMessageRequest) GetState() v11.Message_Metadata_State {
	if x != nil {
		return x.State
	}
	return v11.Message_Metadata_State(0)
}

type AcknowledgeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeMessageResponse) Reset() {
	*x = AcknowledgeMessageResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeMessageResponse) ProtoMessage() {}

func (x *AcknowledgeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeMessageResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{9}
}

func (x *AcknowledgeMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Renew lease period of a message
type RenewMessageLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	LeaseDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewMessageLeaseRequest) Reset() {
	*x = RenewMessageLeaseRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewMessageLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewMessageLeaseRequest) ProtoMessage() {}

func (x *RenewMessageLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewMessageLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewMessageLeaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{10}
}

func (x *RenewMessageLeaseRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RenewMessageLeaseRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RenewMessageLeaseRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

type RenewMessageLeaseResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RemainingTime *durationpb.Duration       `protobuf:"bytes,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	State         v11.Message_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=chronoqueue.api.message.v1.Message_Metadata_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewMessageLeaseResponse) Reset() {
	*x = RenewMessageLeaseResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewMessageLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewMessageLeaseResponse) ProtoMessage() {}

func (x *RenewMessageLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewMessageLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewMessageLeaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{11}
}

func (x *RenewMessageLeaseResponse) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

func (x *RenewMessageLeaseResponse) GetState() v11.Message_Metadata_State {
	if x != nil {
		return x.State
	}
	return v11.Message_Metadata_State(0)
}

// View pending messages on a queueu
type PeekQueueMessagesRequest struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	QueueName     string                                  `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Limit         int64                                   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PriorityRange *PeekQueueMessagesRequest_PriorityRange `protobuf:"bytes,3,opt,name=priority_range,json=priorityRange,proto3,oneof" json:"priority_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekQueueMessagesRequest) Reset() {
	*x = PeekQueueMessagesRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekQueueMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekQueueMessagesRequest) ProtoMessage() {}

func (x *PeekQueueMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekQueueMessagesRequest.ProtoReflect.Descriptor instead.
func (*PeekQueueMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{12}
}

func (x *PeekQueueMessagesRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *PeekQueueMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PeekQueueMessagesRequest) GetPriorityRange() *PeekQueueMessagesRequest_PriorityRange {
	if x != nil {
		return x.PriorityRange
	}
	return nil
}

type PeekQueueMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*v11.Message         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekQueueMessagesResponse) Reset() {
	*x = PeekQueueMessagesResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekQueueMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekQueueMessagesResponse) ProtoMessage() {}

func (x *PeekQueueMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekQueueMessagesResponse.ProtoReflect.Descriptor instead.
func (*PeekQueueMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{13}
}

func (x *PeekQueueMessagesResponse) GetMessages() []*v11.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// vew the state of a given queue
type GetQueueStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStateRequest) Reset() {
	*x = GetQueueStateRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStateRequest) ProtoMessage() {}

func (x *GetQueueStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStateRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{14}
}

func (x *GetQueueStateRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type GetQueueStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StateCounts      map[string]int32       `protobuf:"bytes,1,rep,name=state_counts,json=stateCounts,proto3" json:"state_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EarliestDeadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=earliest_deadline,json=earliestDeadline,proto3" json:"earliest_deadline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetQueueStateResponse) Reset() {
	*x = GetQueueStateResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStateResponse) ProtoMessage() {}

func (x *GetQueueStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStateResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{15}
}

func (x *GetQueueStateResponse) GetStateCounts() map[string]int32 {
	if x != nil {
		return x.StateCounts
	}
	return nil
}

func (x *GetQueueStateResponse) GetEarliestDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.EarliestDeadline
	}
	return nil
}

// send a heartbeat to the queue
type SendMessageHeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageHeartBeatRequest) Reset() {
	*x = SendMessageHeartBeatRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageHeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageHeartBeatRequest) ProtoMessage() {}

func (x *SendMessageHeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageHeartBeatRequest.ProtoReflect.Descriptor instead.
func (*SendMessageHeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{16}
}

func (x *SendMessageHeartBeatRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *SendMessageHeartBeatRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendMessageHeartBeatResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RemainingTime *durationpb.Duration       `protobuf:"bytes,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	State         v11.Message_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=chronoqueue.api.message.v1.Message_Metadata_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageHeartBeatResponse) Reset() {
	*x = SendMessageHeartBeatResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageHeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageHeartBeatResponse) ProtoMessage() {}

func (x *SendMessageHeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageHeartBeatResponse.ProtoReflect.Descriptor instead.
func (*SendMessageHeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{17}
}

func (x *SendMessageHeartBeatResponse) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

func (x *SendMessageHeartBeatResponse) GetState() v11.Message_Metadata_State {
	if x != nil {
		return x.State
	}
	return v11.Message_Metadata_State(0)
}

// List queues
type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{18}
}

func (x *ListQueuesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*v1.Queue            `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{19}
}

func (x *ListQueuesResponse) GetQueues() []*v1.Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

// Create a schedule
type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *v12.Schedule          `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{20}
}

func (x *CreateScheduleRequest) GetSchedule() *v12.Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{21}
}

func (x *CreateScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Delete a schedule
type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type DeleteScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleResponse) Reset() {
	*x = DeleteScheduleResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleResponse) ProtoMessage() {}

func (x *DeleteScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Pause a schedule
type PauseScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleRequest) Reset() {
	*x = PauseScheduleRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleRequest) ProtoMessage() {}

func (x *PauseScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleRequest.ProtoReflect.Descriptor instead.
func (*PauseScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{24}
}

func (x *PauseScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type PauseScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleResponse) Reset() {
	*x = PauseScheduleResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleResponse) ProtoMessage() {}

func (x *PauseScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleResponse.ProtoReflect.Descriptor instead.
func (*PauseScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{25}
}

func (x *PauseScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Resume a schedule
type ResumeScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScheduleRequest) Reset() {
	*x = ResumeScheduleRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScheduleRequest) ProtoMessage() {}

func (x *ResumeScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScheduleRequest.ProtoReflect.Descriptor instead.
func (*ResumeScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{26}
}

func (x *ResumeScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type ResumeScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScheduleResponse) Reset() {
	*x = ResumeScheduleResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScheduleResponse) ProtoMessage() {}

func (x *ResumeScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScheduleResponse.ProtoReflect.Descriptor instead.
func (*ResumeScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{27}
}

func (x *ResumeScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get a schedule
type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{28}
}

func (x *GetScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *v12.Schedule          `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{29}
}

func (x *GetScheduleResponse) GetSchedule() *v12.Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// List schedules
type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{30}
}

func (x *ListSchedulesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*v12.Schedule        `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{31}
}

func (x *ListSchedulesResponse) GetSchedules() []*v12.Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

// Get schedule history
type GetScheduleHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleHistoryRequest) Reset() {
	*x = GetScheduleHistoryRequest{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleHistoryRequest) ProtoMessage() {}

func (x *GetScheduleHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{32}
}

func (x *GetScheduleHistoryRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *GetScheduleHistoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetScheduleHistoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScheduleHistory *v12.ScheduleHistory   `protobuf:"bytes,1,opt,name=schedule_history,json=scheduleHistory,proto3" json:"schedule_history,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetScheduleHistoryResponse) Reset() {
	*x = GetScheduleHistoryResponse{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleHistoryResponse) ProtoMessage() {}

func (x *GetScheduleHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{33}
}

func (x *GetScheduleHistoryResponse) GetScheduleHistory() *v12.ScheduleHistory {
	if x != nil {
		return x.ScheduleHistory
	}
	return nil
}

type PeekQueueMessagesRequest_PriorityRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeekQueueMessagesRequest_PriorityRange) Reset() {
	*x = PeekQueueMessagesRequest_PriorityRange{}
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeekQueueMessagesRequest_PriorityRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeekQueueMessagesRequest_PriorityRange) ProtoMessage() {}

func (x *PeekQueueMessagesRequest_PriorityRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queueservice_v1_request_response_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeekQueueMessagesRequest_PriorityRange.ProtoReflect.Descriptor instead.
func (*PeekQueueMessagesRequest_PriorityRange) Descriptor() ([]byte, []int) {
	return file_proto_queueservice_v1_request_response_proto_rawDescGZIP(), []int{12, 0}
}

func (x *PeekQueueMessagesRequest_PriorityRange) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *PeekQueueMessagesRequest_PriorityRange) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_proto_queueservice_v1_request_response_proto protoreflect.FileDescriptor

const file_proto_queueservice_v1_request_response_proto_rawDesc = "" +
	"\n" +
	",proto/queueservice/v1/request_response.proto\x12\x1fchronoqueue.api.queueservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1aproto/queue/v1/queue.proto\x1a\x1eproto/message/v1/message.proto\x1a proto/schedule/v1/schedule.proto\"\x7f\n" +
	"\x12CreateQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\bmetadata\x18\x02 \x01(\v2'.chronoqueue.api.queue.v1.QueueMetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"/\n" +
	"\x13CreateQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x12DeleteQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"r\n" +
	"\x12PostMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12=\n" +
	"\amessage\x18\x02 \x01(\v2#.chronoqueue.api.message.v1.MessageR\amessage\"/\n" +
	"\x13PostMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x01\n" +
	"\x15GetNextMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12@\n" +
	"\x0elease_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12'\n" +
	"\x0fexclusivity_key\x18\x03 \x01(\tR\x0eexclusivityKey\"W\n" +
	"\x16GetNextMessageResponse\x12=\n" +
	"\amessage\x18\x01 \x01(\v2#.chronoqueue.api.message.v1.MessageR\amessage\"\xa3\x01\n" +
	"\x19AcknowledgeMessageRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12H\n" +
	"\x05state\x18\x03 \x01(\x0e22.chronoqueue.api.message.v1.Message.Metadata.StateR\x05state\"6\n" +
	"\x1aAcknowledgeMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x18RenewMessageLeaseRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12@\n" +
	"\x0elease_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\"\xa7\x01\n" +
	"\x19RenewMessageLeaseResponse\x12@\n" +
	"\x0eremaining_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\rremainingTime\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.chronoqueue.api.message.v1.Message.Metadata.StateR\x05state\"\x8c\x02\n" +
	"\x18PeekQueueMessagesRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12s\n" +
	"\x0epriority_range\x18\x03 \x01(\v2G.chronoqueue.api.queueservice.v1.PeekQueueMessagesRequest.PriorityRangeH\x00R\rpriorityRange\x88\x01\x01\x1a3\n" +
	"\rPriorityRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03maxB\x11\n" +
	"\x0f_priority_range\"\\\n" +
	"\x19PeekQueueMessagesResponse\x12?\n" +
	"\bmessages\x18\x01 \x03(\v2#.chronoqueue.api.message.v1.MessageR\bmessages\"5\n" +
	"\x14GetQueueStateRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"\x8c\x02\n" +
	"\x15GetQueueStateResponse\x12j\n" +
	"\fstate_counts\x18\x01 \x03(\v2G.chronoqueue.api.queueservice.v1.GetQueueStateResponse.StateCountsEntryR\vstateCounts\x12G\n" +
	"\x11earliest_deadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10earliestDeadline\x1a>\n" +
	"\x10StateCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"[\n" +
	"\x1bSendMessageHeartBeatRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\xaa\x01\n" +
	"\x1cSendMessageHeartBeatResponse\x12@\n" +
	"\x0eremaining_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\rremainingTime\x12H\n" +
	"\x05state\x18\x02 \x01(\x0e22.chronoqueue.api.message.v1.Message.Metadata.StateR\x05state\"+\n" +
	"\x11ListQueuesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"M\n" +
	"\x12ListQueuesResponse\x127\n" +
	"\x06queues\x18\x01 \x03(\v2\x1f.chronoqueue.api.queue.v1.QueueR\x06queues\"Z\n" +
	"\x15CreateScheduleRequest\x12A\n" +
	"\bschedule\x18\x01 \x01(\v2%.chronoqueue.api.schedule.v1.ScheduleR\bschedule\"2\n" +
	"\x16CreateScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15DeleteScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"2\n" +
	"\x16DeleteScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x14PauseScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"1\n" +
	"\x15PauseScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15ResumeScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"2\n" +
	"\x16ResumeScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x12GetScheduleRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"X\n" +
	"\x13GetScheduleResponse\x12A\n" +
	"\bschedule\x18\x01 \x01(\v2%.chronoqueue.api.schedule.v1.ScheduleR\bschedule\".\n" +
	"\x14ListSchedulesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\\\n" +
	"\x15ListSchedulesResponse\x12C\n" +
	"\tschedules\x18\x01 \x03(\v2%.chronoqueue.api.schedule.v1.ScheduleR\tschedules\"R\n" +
	"\x19GetScheduleHistoryRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"u\n" +
	"\x1aGetScheduleHistoryResponse\x12W\n" +
	"\x10schedule_history\x18\x01 \x01(\v2,.chronoqueue.api.schedule.v1.ScheduleHistoryR\x0fscheduleHistoryBBZ@github.com/adrien19/chronoqueue/api/queueservice/v1;queueserviceb\x06proto3"

var (
	file_proto_queueservice_v1_request_response_proto_rawDescOnce sync.Once
	file_proto_queueservice_v1_request_response_proto_rawDescData []byte
)

func file_proto_queueservice_v1_request_response_proto_rawDescGZIP() []byte {
	file_proto_queueservice_v1_request_response_proto_rawDescOnce.Do(func() {
		file_proto_queueservice_v1_request_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queueservice_v1_request_response_proto_rawDesc), len(file_proto_queueservice_v1_request_response_proto_rawDesc)))
	})
	return file_proto_queueservice_v1_request_response_proto_rawDescData
}

var file_proto_queueservice_v1_request_response_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_queueservice_v1_request_response_proto_goTypes = []any{
	(*CreateQueueRequest)(nil),                     // 0: chronoqueue.api.queueservice.v1.CreateQueueRequest
	(*CreateQueueResponse)(nil),                    // 1: chronoqueue.api.queueservice.v1.CreateQueueResponse
	(*DeleteQueueRequest)(nil),                     // 2: chronoqueue.api.queueservice.v1.DeleteQueueRequest
	(*DeleteQueueResponse)(nil),                    // 3: chronoqueue.api.queueservice.v1.DeleteQueueResponse
	(*PostMessageRequest)(nil),                     // 4: chronoqueue.api.queueservice.v1.PostMessageRequest
	(*PostMessageResponse)(nil),                    // 5: chronoqueue.api.queueservice.v1.PostMessageResponse
	(*GetNextMessageRequest)(nil),                  // 6: chronoqueue.api.queueservice.v1.GetNextMessageRequest
	(*GetNextMessageResponse)(nil),                 // 7: chronoqueue.api.queueservice.v1.GetNextMessageResponse
	(*AcknowledgeMessageRequest)(nil),              // 8: chronoqueue.api.queueservice.v1.AcknowledgeMessageRequest
	(*AcknowledgeMessageResponse)(nil),             // 9: chronoqueue.api.queueservice.v1.AcknowledgeMessageResponse
	(*RenewMessageLeaseRequest)(nil),               // 10: chronoqueue.api.queueservice.v1.RenewMessageLeaseRequest
	(*RenewMessageLeaseResponse)(nil),              // 11: chronoqueue.api.queueservice.v1.RenewMessageLeaseResponse
	(*PeekQueueMessagesRequest)(nil),               // 12: chronoqueue.api.queueservice.v1.PeekQueueMessagesRequest
	(*PeekQueueMessagesResponse)(nil),              // 13: chronoqueue.api.queueservice.v1.PeekQueueMessagesResponse
	(*GetQueueStateRequest)(nil),                   // 14: chronoqueue.api.queueservice.v1.GetQueueStateRequest
	(*GetQueueStateResponse)(nil),                  // 15: chronoqueue.api.queueservice.v1.GetQueueStateResponse
	(*SendMessageHeartBeatRequest)(nil),            // 16: chronoqueue.api.queueservice.v1.SendMessageHeartBeatRequest
	(*SendMessageHeartBeatResponse)(nil),           // 17: chronoqueue.api.queueservice.v1.SendMessageHeartBeatResponse
	(*ListQueuesRequest)(nil),                      // 18: chronoqueue.api.queueservice.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),                     // 19: chronoqueue.api.queueservice.v1.ListQueuesResponse
	(*CreateScheduleRequest)(nil),                  // 20: chronoqueue.api.queueservice.v1.CreateScheduleRequest
	(*CreateScheduleResponse)(nil),                 // 21: chronoqueue.api.queueservice.v1.CreateScheduleResponse
	(*DeleteScheduleRequest)(nil),                  // 22: chronoqueue.api.queueservice.v1.DeleteScheduleRequest
	(*DeleteScheduleResponse)(nil),                 // 23: chronoqueue.api.queueservice.v1.DeleteScheduleResponse
	(*PauseScheduleRequest)(nil),                   // 24: chronoqueue.api.queueservice.v1.PauseScheduleRequest
	(*PauseScheduleResponse)(nil),                  // 25: chronoqueue.api.queueservice.v1.PauseScheduleResponse
	(*ResumeScheduleRequest)(nil),                  // 26: chronoqueue.api.queueservice.v1.ResumeScheduleRequest
	(*ResumeScheduleResponse)(nil),                 // 27: chronoqueue.api.queueservice.v1.ResumeScheduleResponse
	(*GetScheduleRequest)(nil),                     // 28: chronoqueue.api.queueservice.v1.GetScheduleRequest
	(*GetScheduleResponse)(nil),                    // 29: chronoqueue.api.queueservice.v1.GetScheduleResponse
	(*ListSchedulesRequest)(nil),                   // 30: chronoqueue.api.queueservice.v1.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),                  // 31: chronoqueue.api.queueservice.v1.ListSchedulesResponse
	(*GetScheduleHistoryRequest)(nil),              // 32: chronoqueue.api.queueservice.v1.GetScheduleHistoryRequest
	(*GetScheduleHistoryResponse)(nil),             // 33: chronoqueue.api.queueservice.v1.GetScheduleHistoryResponse
	(*PeekQueueMessagesRequest_PriorityRange)(nil), // 34: chronoqueue.api.queueservice.v1.PeekQueueMessagesRequest.PriorityRange
	nil,                             // 35: chronoqueue.api.queueservice.v1.GetQueueStateResponse.StateCountsEntry
	(*v1.QueueMetadata)(nil),        // 36: chronoqueue.api.queue.v1.QueueMetadata
	(*v11.Message)(nil),             // 37: chronoqueue.api.message.v1.Message
	(*durationpb.Duration)(nil),     // 38: google.protobuf.Duration
	(v11.Message_Metadata_State)(0), // 39: chronoqueue.api.message.v1.Message.Metadata.State
	(*timestamppb.Timestamp)(nil),   // 40: google.protobuf.Timestamp
	(*v1.Queue)(nil),                // 41: chronoqueue.api.queue.v1.Queue
	(*v12.Schedule)(nil),            // 42: chronoqueue.api.schedule.v1.Schedule
	(*v12.ScheduleHistory)(nil),     // 43: chronoqueue.api.schedule.v1.ScheduleHistory
}
var file_proto_queueservice_v1_request_response_proto_depIdxs = []int32{
	36, // 0: chronoqueue.api.queueservice.v1.CreateQueueRequest.metadata:type_name -> chronoqueue.api.queue.v1.QueueMetadata
	37, // 1: chronoqueue.api.queueservice.v1.PostMessageRequest.message:type_name -> chronoqueue.api.message.v1.Message
	38, // 2: chronoqueue.api.queueservice.v1.GetNextMessageRequest.lease_duration:type_name -> google.protobuf.Duration
	37, // 3: chronoqueue.api.queueservice.v1.GetNextMessageResponse.message:type_name -> chronoqueue.api.message.v1.Message
	39, // 4: chronoqueue.api.queueservice.v1.AcknowledgeMessageRequest.state:type_name -> chronoqueue.api.message.v1.Message.Metadata.State
	38, // 5: chronoqueue.api.queueservice.v1.RenewMessageLeaseRequest.lease_duration:type_name -> google.protobuf.Duration
	38, // 6: chronoqueue.api.queueservice.v1.RenewMessageLeaseResponse.remaining_time:type_name -> google.protobuf.Duration
	39, // 7: chronoqueue.api.queueservice.v1.RenewMessageLeaseResponse.state:type_name -> chronoqueue.api.message.v1.Message.Metadata.State
	34, // 8: chronoqueue.api.queueservice.v1.PeekQueueMessagesRequest.priority_range:type_name -> chronoqueue.api.queueservice.v1.PeekQueueMessagesRequest.PriorityRange
	37, // 9: chronoqueue.api.queueservice.v1.PeekQueueMessagesResponse.messages:type_name -> chronoqueue.api.message.v1.Message
	35, // 10: chronoqueue.api.queueservice.v1.GetQueueStateResponse.state_counts:type_name -> chronoqueue.api.queueservice.v1.GetQueueStateResponse.StateCountsEntry
	40, // 11: chronoqueue.api.queueservice.v1.GetQueueStateResponse.earliest_deadline:type_name -> google.protobuf.Timestamp
	38, // 12: chronoqueue.api.queueservice.v1.SendMessageHeartBeatResponse.remaining_time:type_name -> google.protobuf.Duration
	39, // 13: chronoqueue.api.queueservice.v1.SendMessageHeartBeatResponse.state:type_name -> chronoqueue.api.message.v1.Message.Metadata.State
	41, // 14: chronoqueue.api.queueservice.v1.ListQueuesResponse.queues:type_name -> chronoqueue.api.queue.v1.Queue
	42, // 15: chronoqueue.api.queueservice.v1.CreateScheduleRequest.schedule:type_name -> chronoqueue.api.schedule.v1.Schedule
	42, // 16: chronoqueue.api.queueservice.v1.GetScheduleResponse.schedule:type_name -> chronoqueue.api.schedule.v1.Schedule
	42, // 17: chronoqueue.api.queueservice.v1.ListSchedulesResponse.schedules:type_name -> chronoqueue.api.schedule.v1.Schedule
	43, // 18: chronoqueue.api.queueservice.v1.GetScheduleHistoryResponse.schedule_history:type_name -> chronoqueue.api.schedule.v1.ScheduleHistory
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_queueservice_v1_request_response_proto_init() }
func file_proto_queueservice_v1_request_response_proto_init() {
	if File_proto_queueservice_v1_request_response_proto != nil {
		return
	}
	file_proto_queueservice_v1_request_response_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_queueservice_v1_request_response_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queueservice_v1_request_response_proto_rawDesc), len(file_proto_queueservice_v1_request_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_queueservice_v1_request_response_proto_goTypes,
		DependencyIndexes: file_proto_queueservice_v1_request_response_proto_depIdxs,
		MessageInfos:      file_proto_queueservice_v1_request_response_proto_msgTypes,
	}.Build()
	File_proto_queueservice_v1_request_response_proto = out.File
	file_proto_queueservice_v1_request_response_proto_goTypes = nil
	file_proto_queueservice_v1_request_response_proto_depIdxs = nil
}
